name: Pylint

on: 
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: autopep8
      id: autopep8
      uses: peter-evans/autopep8@v1
      with:
        args: --recursive --in-place --aggressive --aggressive .
    
    
  
